import {
  Receipt,
  Home,
  Car,
  ShoppingCart,
  Utensils,
  Wine,
  Plane,
  Heart,
  Wallet,
  Briefcase,
  Smartphone,
  Scissors,
  DollarSign,
  Gift,
  Coffee,
  Bus,
  Shirt,
  Gamepad2,
  GraduationCap,
  Stethoscope,
  Baby,
  Dog,
  Dumbbell,
  Music,
  Book,
  Film,
  Wrench,
  Paintbrush,
  Bike,
  type LucideIcon,
} from "lucide-react";

export const categoryIcons: Record<string, LucideIcon> = {
  receipt: Receipt,
  home: Home,
  car: Car,
  "shopping-cart": ShoppingCart,
  utensils: Utensils,
  wine: Wine,
  plane: Plane,
  heart: Heart,
  wallet: Wallet,
  briefcase: Briefcase,
  smartphone: Smartphone,
  scissors: Scissors,
  "dollar-sign": DollarSign,
  gift: Gift,
  coffee: Coffee,
  bus: Bus,
  shirt: Shirt,
  gamepad: Gamepad2,
  "graduation-cap": GraduationCap,
  stethoscope: Stethoscope,
  baby: Baby,
  dog: Dog,
  dumbbell: Dumbbell,
  music: Music,
  book: Book,
  film: Film,
  wrench: Wrench,
  paintbrush: Paintbrush,
  bike: Bike,
};